version: '3.8'

services:
  bim-library:
    build: .
    ports:
      - "80:80"
    container_name: bim-element-library
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    
  # Optional: Add nginx proxy for SSL and domain
  # nginx-proxy:
  #   image: nginxproxy/nginx-proxy
  #   ports:
  #     - "443:443"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #     - ./certs:/etc/nginx/certs
  #   environment:
  #     - DEFAULT_HOST=yourdomain.com